AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the tables used for gift-giver-server
Parameters:
  stack:
    Type: String
    Default: -int
  UsersTableReadCapacityUnits:
    Default: '5'
    Type: Number
    MinValue: '1'
  UsersTableWriteCapacityUnits:
    Default: '5'
    Type: Number
    MinValue: '1'
Resources:
  giftGiverUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub gift-giver-users${stack}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'UsersTableReadCapacityUnits'
        WriteCapacityUnits: !Ref 'UsersTableWriteCapacityUnits'
